# This file is part of the ProVANT simulator project. Licensed under the terms of the MIT open source license. More
# details at https://github.com/Guiraffo/ProVANT-Simulator/blob/master/LICENSE.md

controller_joint_names: ['Rotor_R_joint_name', 'Hel_R_joint_name', 'Rotor_L_joint_name', 'Hel_L_joint_name', 'Rudder_R_joint_name', 'Rudder_L_joint_name', 'Aileron_R_joint_name', 'Aileron_L_joint_name', ]
